require("dotenv").config();
const { Resend } = require("resend");
const ContactModel = require("../Models/ContactModel");
const EnviroModel = require("../Models/EnviroModel");

// Initialize Resend
const resend = new Resend(process.env.RESEND_API_KEY);

/* ================= CONTACT CONTROLLER ================= */
const ContactController = async (req, res) => {
  try {
    const { name, email, message } = req.body;

    // Save to DB
    const newContact = new ContactModel({ name, email, message });
    await newContact.save();

    // Send Email using Resend
    await resend.emails.send({
      from: "Enviro<notification.envirosafetyglass.com>", //  verified sender
      to: process.env.ENVIRO_OWNER_EMAIL,
      subject: `📬 New Contact Message from ${name}`,
      html: `
        <div style="font-family: Arial, sans-serif; padding: 20px; border: 1px solid #eaeaea; border-radius: 10px; background: #f9f9f9; max-width: 600px; margin: auto;">
          <h2 style="color: #2c3e50;">📩 New Contact Form Submission</h2>
          <p><strong>Name:</strong> ${name}</p>
          <p><strong>Email:</strong> ${email}</p>
          <p><strong>Message:</strong></p>
          <div style="background: #fff; padding: 15px; border-radius: 5px; border: 1px solid #ccc;">
            ${message}
          </div>
        </div>
      `,
    });

    res.status(201).json({
      message: "Contact entry created and email sent successfully via SendGrid API",
    });
  } catch (error) {
    console.error("Error creating contact entry:", error);
    res.status(500).json({ error: "Internal server error" });
  }
};

/* ================= ENVIRO CONTROLLER ================= */
const enviroController = async (req, res) => {
  try {
    const { name, email, phone, subject, message } = req.body;

    // Validate required fields
    if (!name || !email || !subject || !message) {
      return res
        .status(400)
        .json({ error: "Missing required contact fields (name, email, subject, message)." });
    }

    // Save to DB
    const newContact = new EnviroModel({ name, email, phone, subject, message });
    await newContact.save();
    console.log("Contact entry saved to database successfully.");

    // Send Email via Resend
    try {
      await resend.emails.send({
        from: "Enviro <onboarding@resend.dev>", // ✅ verified sender
        to: process.env.ENVIRO_OWNER_EMAIL,
        subject: `📬 New Contact Message from ${name} (via Enviro App)`,
        html: `
          <div style="font-family: 'Inter', Arial, sans-serif; padding: 20px; border: 1px solid #e0e0e0; border-radius: 12px; background: #ffffff; max-width: 600px; margin: auto; box-shadow: 0 4px 8px rgba(0,0,0,0.05);">
            <h2 style="color: #1a73e8; border-bottom: 2px solid #1a73e8; padding-bottom: 10px;">
              📩 New Contact Form Submission
            </h2>
            <table style="width: 100%; margin-top: 15px;">
              <tr><td><strong>Name:</strong></td><td>${name}</td></tr>
              <tr><td><strong>Email:</strong></td><td><a href="mailto:${email}">${email}</a></td></tr>
              <tr><td><strong>Phone:</strong></td><td>${phone || "N/A"}</td></tr>
              <tr><td><strong>Subject:</strong></td><td>${subject}</td></tr>
            </table>
            <p style="margin-top: 20px;"><strong>Message:</strong></p>
            <div style="background: #f4f4f9; padding: 15px; border-radius: 8px; border-left: 5px solid #1a73e8;">
              ${message}
            </div>
            <p style="font-size: 12px; color: #777; margin-top: 25px; text-align: center;">
              This message was automatically generated by the Enviro contact form.
            </p>
          </div>
        `,
      });

      console.log("Email sent successfully via Resend.");
    } catch (emailError) {
      console.error("--- RESEND API ERROR ---");
      console.error(emailError);
      return res.status(500).json({
        error:
          "Contact saved to database, but failed to send notification email. Check server logs.",
      });
    }

    res.status(201).json({
      message: "Contact entry created and email sent successfully.",
    });
  } catch (dbError) {
    console.error("--- DATABASE ERROR ---", dbError);
    res.status(500).json({
      error: "Internal server error: Failed to process request or save to database.",
    });
  }
};

module.exports = { ContactController, enviroController };
